#cloud-config
cloud_config_modules:
- disk_setup
- mounts

fs_setup:
- label: etcd_storage
  filesystem: xfs
  device: /dev/xvdc
  partition: auto
- label: emptydir
  filesystem: xfs
  device: /dev/xvdd
  partition: auto

runcmd:
- mkdir -p /var/lib/etcd
- mkdir -p /var/lib/origin/openshift.local.volumes

mounts:
- [ /dev/xvdc, /var/lib/etcd, xfs, "defaults" ]
- [ /dev/xvdd, /var/lib/origin/openshift.local.volumes, xfs, "defaults,gquota" ]

write_files:
- content: |
    DEVS='/dev/xvdb'
    VG=docker_vol
    DATA_SIZE=95%VG
    STORAGE_DRIVER=devicemapper
    ROOT_SIZE=45G
    GROWPART=true
    EXTRA_DOCKER_STORAGE_OPTIONS='--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker_vg-docker--pool'
  path: /etc/sysconfig/docker-storage-setup
  owner: root:root

users:
- default

system_info:
  default_user:
    name: ec2-user
